<!DOCTYPE html>
<html lang="hu">
<head>
<meta charset="utf-8">
<title>Érdességi térképek – Szamos</title>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/>

<style>
  body { margin:0; }
  #map { height: 100vh; }
</style>
</head>

<body>

<div id="map"></div>

<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>

<script>
  var map = L.map('map').setView([47.9, 22.6], 12);

  // GOOGLE SATELLITE HÁTTÉR
  L.tileLayer(
    'https://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',
    {
      maxZoom: 20,
      subdomains:['mt0','mt1','mt2','mt3']
    }
  ).addTo(map);
</script>

</body>
</html>
